-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 23:35:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema compras
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `compras` ;

-- -----------------------------------------------------
-- Schema compras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compras` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `compras` ;

-- -----------------------------------------------------
-- Table `compras`.`tipo_plan_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`tipo_plan_pago` ;

CREATE TABLE IF NOT EXISTS `compras`.`tipo_plan_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `abreviacion` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`planes_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`planes_pago` ;

CREATE TABLE IF NOT EXISTS `compras`.`planes_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mensualidades` INT NULL,
  `notas` VARCHAR(45) NULL,
  `tipo` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_planes_tipo_planes_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_planes_tipo_planes`
    FOREIGN KEY (`tipo`)
    REFERENCES `compras`.`tipo_plan_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`compras` ;

CREATE TABLE IF NOT EXISTS `compras`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `idVendedor` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `descuento` DOUBLE NOT NULL DEFAULT 0.0,
  `plan_pagos` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_plan_pagos_idx` (`plan_pagos` ASC) VISIBLE,
  CONSTRAINT `fk_compras_plan_pagos`
    FOREIGN KEY (`plan_pagos`)
    REFERENCES `compras`.`planes_pago` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`.`productos_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compras`.`productos_compra` ;

CREATE TABLE IF NOT EXISTS `compras`.`productos_compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCompra` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `costo` DOUBLE NOT NULL DEFAULT 0.0,
  `notas` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_compras_idx` (`idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_id_compras`
    FOREIGN KEY (`idCompra`)
    REFERENCES `compras`.`compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'admin' IDENTIFIED BY 'admin';
-- GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `compras`.`tipo_plan_pago`
-- -----------------------------------------------------
START TRANSACTION;
USE `compras`;
INSERT INTO `compras`.`tipo_plan_pago` (`id`, `nombre`, `abreviacion`) VALUES (1, 'Presupuesto', 'prs');
INSERT INTO `compras`.`tipo_plan_pago` (`id`, `nombre`, `abreviacion`) VALUES (2, 'Meses sin intereses', 'msi');
INSERT INTO `compras`.`tipo_plan_pago` (`id`, `nombre`, `abreviacion`) VALUES (3, 'Mensualidades fijas', 'mfs');

COMMIT;

